upstreamProjects:
  Mule-runtime/mule/4.9.6-WITH-W-18622349
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
