upstreamProjects:
  Mule-runtime/mule/master-TESTCYCLE-2020-DRY-RUN
  Mule-runtime/mule-http-netty-service/master
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
