upstreamProjects:
  Mule-runtime/mule/4.8.6-DRY-RUN
# TODO W-17404141: Uncomment once mule-sdk-api and mule-sdk-compatibility-api are deployed to public repos
# mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
