upstreamProjects:
  Mule-runtime/mule/master-OCTOBER-2023
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
